### ISSUE TITLE
GraphDBModel.findOne returns first document when none match

### ISSUE THREAD

**Issue by htysc** [csse-uoft/graphdb-utils#3]
When GraphDBModel.findOne's filter doesn't match any of the available documents, it appears to return the first document by ID instead of undefined or null. This has led to a few bugs when I've worked on SNM-I. Is this the expected result?

**Comment by LesterLyu** [comment]
Will look into that

**Comment by LesterLyu** [comment]
I cannot reproduce this issue: https://github.com/csse-uoft/graphdb-utils/commit/1cac12f94734845624e13fadf80b2ab70f9457cb
